import 'pharmacy_model.dart';

List<Pharmacy> pharmacySamples = [
  Pharmacy(
    name: "Creatine Monohydrate",
    type: "Bột",
    quantity: 300, // gram
    price: 550000,
    usage: "Pha 5g với nước, dùng trước hoặc sau khi tập.",
    note: "Tăng sức mạnh, hỗ trợ tăng cơ",
    brand: "MyProtein",
    origin: "UK",
    ingredient: "Creatine Monohydrate 100%",
    effect: "Tăng sức bền, tăng hiệu suất tập luyện",
    sideEffects: "Đầy bụng nếu uống không đủ nước",
    storage: "Bảo quản nơi khô ráo, tránh ánh nắng",
    expiryDate: "2026-10-01",
    imageUrl: "assets/pharmacy/monohydrate.webp",
  ),
  Pharmacy(
    name: "L-Carnitine 500mg",
    type: "Viên nang",
    quantity: 60,
    price: 420000,
    usage: "Dùng 1 viên trước khi tập 30 phút.",
    note: "Hỗ trợ đốt mỡ, tăng chuyển hóa",
    brand: "Applied Nutrition",
    origin: "USA",
    ingredient: "L-Carnitine Tartrate 500mg",
    effect: "Đốt mỡ, tăng năng lượng",
    sideEffects: "Mất ngủ nếu dùng tối muộn",
    storage: "Để nơi mát, tránh ẩm",
    expiryDate: "2026-06-30",
    imageUrl: "assets/pharmacy/lcarnitine.webp",
  ),
  Pharmacy(
    name: "Zinc Gluconate",
    type: "Viên nén",
    quantity: 100,
    price: 190000,
    usage: "Uống 1 viên sau ăn sáng.",
    note: "Tăng testosterone tự nhiên, hỗ trợ phục hồi",
    brand: "Now Foods",
    origin: "USA",
    ingredient: "Kẽm gluconat 50mg",
    effect: "Tăng miễn dịch, cải thiện sinh lý",
    sideEffects: "Buồn nôn nếu uống lúc đói",
    storage: "Nơi khô ráo, tránh ánh sáng",
    expiryDate: "2027-02-01",
    imageUrl: "assets/pharmacy/zinc.webp",
  ),
  Pharmacy(
    name: "BCAA 2:1:1",
    type: "Bột",
    quantity: 250, // gram
    price: 650000,
    usage: "Pha 1 muỗng (~10g) với nước, dùng trong khi tập.",
    note: "Chống dị hóa, hỗ trợ phục hồi",
    brand: "Rule 1",
    origin: "USA",
    ingredient: "Leucine, Isoleucine, Valine (2:1:1)",
    effect: "Giảm đau cơ, duy trì cơ bắp",
    sideEffects: "Có thể gây kích thích nếu dùng quá liều",
    storage: "Nơi khô mát, kín gió",
    expiryDate: "2027-01-15",
    imageUrl: "assets/pharmacy/bcaa.webp",
  ),
  Pharmacy(
    name: "Joint Support Formula",
    type: "Viên nang",
    quantity: 90,
    price: 390000,
    usage: "Uống 1–2 viên/ngày sau ăn",
    note: "Hỗ trợ xương khớp khi tập nặng",
    brand: "OstroVit",
    origin: "Ba Lan",
    ingredient: "Glucosamine, Chondroitin, MSM",
    effect: "Giảm đau khớp, tăng linh hoạt",
    sideEffects: "Buồn nôn nhẹ, cần dùng sau ăn",
    storage: "Tránh nhiệt độ cao, đậy kín sau dùng",
    expiryDate: "2026-11-10",
    imageUrl: "assets/pharmacy/joint.webp",
  ),
  Pharmacy(
    name: "Salonpas Spray",
    type: "Xịt nóng",
    quantity: 80,
    price: 115000,
    usage: "Xịt trực tiếp lên vùng đau 3–4 lần/ngày",
    note: "Giúp làm ấm cơ, giảm đau khi vận động",
    brand: "Hisamitsu",
    origin: "Nhật Bản",
    ingredient: "Methyl salicylate, Menthol, Camphor",
    effect: "Giảm đau cơ, khớp, căng cơ",
    sideEffects: "Kích ứng da nhẹ, không dùng vết thương hở",
    storage: "Nơi khô ráo, tránh ánh nắng",
    expiryDate: "2026-06-30",
    imageUrl: "assets/pharmacy/salonpas.webp",
  ),
  Pharmacy(
    name: "ICE Spray",
    type: "Xịt lạnh",
    quantity: 100,
    price: 98000,
    usage: "Xịt lên vùng đau từ khoảng cách 15cm",
    note: "Hạ nhiệt nhanh, dùng ngay sau chấn thương",
    brand: "Eagle Brand",
    origin: "Singapore",
    ingredient: "Menthol, Ethanol, Propane",
    effect: "Giảm sưng, đau cấp tính, chấn thương nhẹ",
    sideEffects: "Rát nhẹ, không xịt quá lâu tại một điểm",
    storage: "Tránh nhiệt độ cao, không đâm thủng bình",
    expiryDate: "2025-12-20",
    imageUrl: "assets/pharmacy/icespray.webp",
  ),

];
