import 'package:fitjourney/features/notebook/exercises/exercises_model.dart';

// === Nhóm: Cơ Chân ===
final List<Exercise> legExercises = [
  Exercise(
      name: "Squat",
      description: "Tăng sức mạnh đùi và mông, có thể dùng tạ hoặc không.",
      duration: 5,
      category: "Chân",
      difficulty: "Trung bình",
      equipment: "Không hoặc tạ đòn",
      muscles: "Mông, Đùi trước",
      caloriesBurned: "90 kcal/10 phút",
      imageUrl: "https://i.pinimg.com/originals/ff/fb/5a/fffb5a09d3c6f97b4329faaa35977f6d.jpg"),
  Exercise(
      name: "Lunges",
      description: "Cải thiện độ cân bằng và cơ đùi, mông.",
      duration: 4,
      category: "Chân",
      difficulty: "Trung bình",
      equipment: "Không hoặc tạ đơn",
      muscles: "Đùi, Mông",
      caloriesBurned: "95 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.8nyKmagJvWS3bPDD4gvyzAHaFo?rs=1"),
  Exercise(
      name: "Step-Up",
      description: "Bước lên ghế hoặc bục để rèn luyện đùi và mông.",
      duration: 3,
      category: "Chân",
      difficulty: "Dễ",
      equipment: "Ghế chắc chắn",
      muscles: "Đùi trước, Mông",
      caloriesBurned: "85 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.x-WKgI7FRAe9tHqMFMfcswHaFj?rs=1"),
  Exercise(
      name: "Leg Press",
      description: "Dùng máy đẩy chân để phát triển cơ đùi và bắp chân.",
      duration: 4,
      category: "Chân",
      difficulty: "Khó",
      equipment: "Máy Leg Press",
      muscles: "Đùi trước, Bắp chân",
      caloriesBurned: "100 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.GD95sVCl4lDg4RAY6i0ovgHaEK?rs=1"),
  Exercise(
      name: "Bulgarian Split Squat",
      description: "Biến thể của squat nhấn mạnh vào từng chân riêng biệt.",
      duration: 4,
      category: "Chân",
      difficulty: "Khó",
      equipment: "Ghế + Tạ đơn",
      muscles: "Đùi trước, Mông",
      caloriesBurned: "95 kcal/10 phút",
      imageUrl: "https://tse2.mm.bing.net/th/id/OIP.6M8L7jUZvXJUFfUQkEqOhgHaHa?rs=1"),
  Exercise(
      name: "Deadlift",
      description: "Bài tập toàn thân, nhấn mạnh đùi sau và lưng dưới.",
      duration: 5,
      category: "Chân",
      difficulty: "Khó",
      equipment: "Tạ đòn",
      muscles: "Đùi sau, Lưng dưới",
      caloriesBurned: "110 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.VC_bKfQ-Wac_6V8UhFsncgHaEK?rs=1"),
  Exercise(
      name: "Calf Raises",
      description: "Tăng sức mạnh và độ săn chắc cho bắp chân.",
      duration: 3,
      category: "Chân",
      difficulty: "Dễ",
      equipment: "Không hoặc tạ",
      muscles: "Bắp chân",
      caloriesBurned: "50 kcal/10 phút",
      imageUrl: "https://tse2.mm.bing.net/th/id/OIP.9VxR1zHZPf3AtmUljFdUUgHaHa?rs=1"),
  Exercise(
      name: "Wall Sit",
      description: "Giữ tư thế ngồi tựa tường để siết cơ đùi.",
      duration: 2,
      category: "Chân",
      difficulty: "Trung bình",
      equipment: "Tường",
      muscles: "Đùi trước",
      caloriesBurned: "55 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.zuvSBQg5x0MPm1FsLqUh8QHaFj?rs=1"),
  Exercise(
      name: "Glute Ham Raise",
      description: "Tác động sâu vào đùi sau và mông.",
      duration: 4,
      category: "Chân",
      difficulty: "Khó",
      equipment: "Máy GHR",
      muscles: "Đùi sau, Mông",
      caloriesBurned: "90 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.ZIqJ3FVPA_gnxUzwNf2ChAHaHa?rs=1"),
  Exercise(
      name: "Reverse Lunge",
      description: "Biến thể lunge giúp tăng sự ổn định và kiểm soát.",
      duration: 4,
      category: "Chân",
      difficulty: "Trung bình",
      equipment: "Tạ đơn (tuỳ chọn)",
      muscles: "Đùi, Mông",
      caloriesBurned: "85 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.mN1Vn6HZVl-5hxCJ7YLBYQHaFj?rs=1"),
];

// === Nhóm: Cơ Mông ===
final List<Exercise> gluteExercises = [
  Exercise(
      name: "Glute Bridge",
      description: "Tăng cường cơ mông và lưng dưới.",
      duration: 4,
      category: "Mông",
      difficulty: "Dễ",
      equipment: "Không",
      muscles: "Mông, Lưng dưới",
      caloriesBurned: "70 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.CpwsT_spgJ8OWTJmyQkacQHaFj?rs=1"),
  Exercise(
      name: "Donkey Kicks",
      description: "Bài tập mông nhẹ nhàng cho người mới.",
      duration: 3,
      category: "Mông",
      difficulty: "Dễ",
      equipment: "Không",
      muscles: "Mông",
      caloriesBurned: "60 kcal/10 phút",
      imageUrl: "https://tse2.mm.bing.net/th/id/OIP.5boHwcYmaS5v8rHd0iLmnQHaFt?rs=1"),
  Exercise(
      name: "Hip Thrust",
      description: "Tăng cơ mông hiệu quả với tạ đòn.",
      duration: 4,
      category: "Mông",
      difficulty: "Trung bình",
      equipment: "Tạ đòn",
      muscles: "Mông",
      caloriesBurned: "90 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.cGVQ6Ft2D8zRtRf41CDY6QHaE8?rs=1"),
  Exercise(
      name: "Sumo Squat",
      description: "Biến thể squat với tư thế chân rộng.",
      duration: 4,
      category: "Mông",
      difficulty: "Trung bình",
      equipment: "Tạ đơn",
      muscles: "Mông, Đùi trong",
      caloriesBurned: "85 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.DX9ewEfg0DWzOCswZOV6bgHaE8?rs=1"),
  Exercise(
      name: "Side-Lying Leg Raise",
      description: "Nâng chân sang ngang để kích hoạt mông.",
      duration: 3,
      category: "Mông",
      difficulty: "Dễ",
      equipment: "Không",
      muscles: "Mông ngoài",
      caloriesBurned: "55 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.6r8xQOdGTjV4eFPA2loZ5wHaEK?rs=1"),
  Exercise(
      name: "Clamshells",
      description: "Bài tập mông nhẹ nhàng nằm nghiêng.",
      duration: 3,
      category: "Mông",
      difficulty: "Dễ",
      equipment: "Dây kháng lực",
      muscles: "Mông ngoài",
      caloriesBurned: "50 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.bG1fslmcF1AUKzMTdKaK6gHaHa?rs=1"),
  Exercise(
      name: "Frog Pump",
      description: "Tăng sức mạnh mông dưới bằng tư thế ếch.",
      duration: 3,
      category: "Mông",
      difficulty: "Dễ",
      equipment: "Không",
      muscles: "Mông",
      caloriesBurned: "55 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.2W0dAsCS8do_TFLK9x4Y6wHaE8?rs=1"),
  Exercise(
      name: "Cable Kickback",
      description: "Dùng máy kéo để đá chân sau.",
      duration: 4,
      category: "Mông",
      difficulty: "Trung bình",
      equipment: "Máy cáp",
      muscles: "Mông",
      caloriesBurned: "75 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.uNU4oKj6UBADYv3Kk4Ez3AHaFj?rs=1"),
  Exercise(
      name: "Single-Leg Glute Bridge",
      description: "Biến thể bridge giúp siết mông mạnh hơn.",
      duration: 4,
      category: "Mông",
      difficulty: "Trung bình",
      equipment: "Không",
      muscles: "Mông",
      caloriesBurned: "70 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.AV4uMK1x4HyGWKqa9kkMAwHaEK?rs=1"),
  Exercise(
      name: "Fire Hydrant",
      description: "Đá chân sang ngang như chó tè để kích hoạt mông ngoài.",
      duration: 3,
      category: "Mông",
      difficulty: "Dễ",
      equipment: "Không",
      muscles: "Mông ngoài",
      caloriesBurned: "60 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.DMyw3k3En2Z7V4OTijVq3QHaHa?rs=1"),
];

final List<Exercise> armExercises = [
  Exercise(
      name: "Bicep Curl",
      description: "Tập trung vào cơ tay trước, dùng tạ đơn hoặc tạ đòn.",
      duration: 3,
      category: "Tay",
      difficulty: "Dễ",
      equipment: "Tạ đơn",
      muscles: "Tay trước (Biceps)",
      caloriesBurned: "60 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.-NL131FJI8jT9k1XtEqi6gHaE8?rs=1"),
  Exercise(
      name: "Tricep Dips",
      description: "Tập cơ tay sau với ghế hoặc thanh ngang.",
      duration: 3,
      category: "Tay",
      difficulty: "Trung bình",
      equipment: "Ghế/Thùng",
      muscles: "Tay sau (Triceps)",
      caloriesBurned: "65 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.N35o8Hgg6Hcci0_OzI5zGwHaHa?rs=1"),
  Exercise(
      name: "Hammer Curl",
      description: "Giống bicep curl nhưng thay đổi tư thế cầm tạ để tăng độ kích thích.",
      duration: 3,
      category: "Tay",
      difficulty: "Trung bình",
      equipment: "Tạ đơn",
      muscles: "Tay trước",
      caloriesBurned: "60 kcal/10 phút",
      imageUrl: "https://tse2.mm.bing.net/th/id/OIP.xep6-FVnTwcV1ty9X5a4yQHaE8?rs=1"),
  Exercise(
      name: "Concentration Curl",
      description: "Bài tập tập trung, thực hiện từng tay.",
      duration: 4,
      category: "Tay",
      difficulty: "Trung bình",
      equipment: "Tạ đơn",
      muscles: "Tay trước",
      caloriesBurned: "62 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.ghoaN7FtUl9QaXIXz7VdJwHaFj?rs=1"),
  Exercise(
      name: "Tricep Kickback",
      description: "Kéo tay ra sau để siết chặt cơ tay sau.",
      duration: 4,
      category: "Tay",
      difficulty: "Trung bình",
      equipment: "Tạ đơn",
      muscles: "Tay sau",
      caloriesBurned: "60 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.BpO1T2_oF3mtF_HJD2TcmAHaHa?rs=1"),
  Exercise(
      name: "Barbell Curl",
      description: "Bài tập cổ điển với tạ đòn cho tay trước.",
      duration: 4,
      category: "Tay",
      difficulty: "Trung bình",
      equipment: "Tạ đòn",
      muscles: "Tay trước",
      caloriesBurned: "65 kcal/10 phút",
      imageUrl: "https://tse2.mm.bing.net/th/id/OIP.oNszGnQyZhyRQGu6g7bHdAHaHa?rs=1"),
  Exercise(
      name: "Overhead Tricep Extension",
      description: "Duỗi tay sau qua đầu để tăng độ căng.",
      duration: 3,
      category: "Tay",
      difficulty: "Trung bình",
      equipment: "Tạ đơn",
      muscles: "Tay sau",
      caloriesBurned: "58 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.zxCkY2F6Q12zkYdl-MrQLQHaHa?rs=1"),
  Exercise(
      name: "Cable Pushdown",
      description: "Dùng máy kéo để tác động mạnh lên tay sau.",
      duration: 4,
      category: "Tay",
      difficulty: "Khó",
      equipment: "Máy kéo cáp",
      muscles: "Tay sau",
      caloriesBurned: "70 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.3zPHIH5sf_7U-YFkFVKnHgHaEK?rs=1"),
  Exercise(
      name: "Preacher Curl",
      description: "Bài tập tập trung cô lập biceps trên ghế nghiêng.",
      duration: 3,
      category: "Tay",
      difficulty: "Trung bình",
      equipment: "Ghế preacher + tạ",
      muscles: "Tay trước",
      caloriesBurned: "62 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.jHgRa3ZKHTv9hvLEmOMBLwHaEK?rs=1"),
  Exercise(
      name: "Zottman Curl",
      description: "Kết hợp curl xuôi và ngửa để tác động cả biceps và forearm.",
      duration: 4,
      category: "Tay",
      difficulty: "Trung bình",
      equipment: "Tạ đơn",
      muscles: "Tay trước + Cẳng tay",
      caloriesBurned: "65 kcal/10 phút",
      imageUrl: "https://tse4.mm.bing.net/th/id/OIP.jAvW_O0-PgTQ2lWcYe_FNgHaE8?rs=1"),
];

final List<Exercise> chestExercises = [
  Exercise(
      name: "Push-up",
      description: "Cơ bản và hiệu quả cho ngực và tay.",
      duration: 3,
      category: "Ngực",
      difficulty: "Dễ",
      equipment: "Không",
      muscles: "Ngực, Vai, Tay sau",
      caloriesBurned: "75 kcal/10 phút",
      imageUrl: "https://bizweb.dktcdn.net/100/011/344/files/tap-gym-tai-nha-2.jpg?v=1644567096810"),
  Exercise(
      name: "Chest Press",
      description: "Bài tập ngực với tạ đơn hoặc máy.",
      duration: 4,
      category: "Ngực",
      difficulty: "Trung bình",
      equipment: "Tạ đơn hoặc máy",
      muscles: "Ngực giữa",
      caloriesBurned: "85 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.1uHmOE6ByVUylfevDdyUHQAAAA?rs=1"),
  Exercise(
      name: "Incline Dumbbell Press",
      description: "Tăng cường phần ngực trên.",
      duration: 4,
      category: "Ngực",
      difficulty: "Trung bình",
      equipment: "Tạ đơn",
      muscles: "Ngực trên",
      caloriesBurned: "80 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.eGpMiO6PgSpPPkD1T9EPWQHaEK?rs=1"),
  Exercise(
      name: "Decline Push-up",
      description: "Tập trung vào ngực dưới.",
      duration: 3,
      category: "Ngực",
      difficulty: "Trung bình",
      equipment: "Không",
      muscles: "Ngực dưới",
      caloriesBurned: "70 kcal/10 phút",
      imageUrl: "https://tse2.mm.bing.net/th/id/OIP.L7hUhKOf7EJxwNdNMcDwGQHaE8?rs=1"),
  Exercise(
      name: "Cable Crossover",
      description: "Tăng cường độ nét ngực với máy kéo cáp.",
      duration: 4,
      category: "Ngực",
      difficulty: "Trung bình",
      equipment: "Máy kéo cáp",
      muscles: "Ngực giữa",
      caloriesBurned: "85 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.T2qjcEGVMUGo8hWWOuPNzwHaEK?rs=1"),
  Exercise(
      name: "Dumbbell Fly",
      description: "Mở rộng ngực với chuyển động vòng cung.",
      duration: 3,
      category: "Ngực",
      difficulty: "Trung bình",
      equipment: "Tạ đơn",
      muscles: "Ngực",
      caloriesBurned: "75 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.-yDFjGi5ExvBoVXpQNdW9QHaE8?rs=1"),
  Exercise(
      name: "Bench Press",
      description: "Bài tập ngực tổng thể với tạ đòn.",
      duration: 4,
      category: "Ngực",
      difficulty: "Trung bình",
      equipment: "Tạ đòn",
      muscles: "Ngực, Tay, Vai",
      caloriesBurned: "90 kcal/10 phút",
      imageUrl: "https://tse2.mm.bing.net/th/id/OIP.DOPkKDj5G2ZcCBm7EBQAjwHaE8?rs=1"),
  Exercise(
      name: "Pec Deck Machine",
      description: "Máy tập cô lập cơ ngực hiệu quả.",
      duration: 3,
      category: "Ngực",
      difficulty: "Dễ",
      equipment: "Máy Pec Deck",
      muscles: "Ngực giữa",
      caloriesBurned: "70 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.8zM-FjGPxEPrPUnJg1-JhAHaEK?rs=1"),
  Exercise(
      name: "Wide Push-up",
      description: "Tăng độ tác động lên ngực bằng cách đặt tay rộng hơn.",
      duration: 3,
      category: "Ngực",
      difficulty: "Dễ",
      equipment: "Không",
      muscles: "Ngực ngoài",
      caloriesBurned: "72 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.QrAOv_9y1EDzZEDRQ5VZ3AHaE8?rs=1"),
  Exercise(
      name: "Svend Press",
      description: "Bài tập ngực không cần tạ nặng, tăng siết cơ.",
      duration: 2,
      category: "Ngực",
      difficulty: "Dễ",
      equipment: "Đĩa tạ nhẹ",
      muscles: "Ngực giữa",
      caloriesBurned: "60 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.bshNWTTzC7gbvHT_AQm81gHaE8?rs=1"),
];

// === Nhóm: Cơ Bụng ===
final List<Exercise> coreExercises = [
  Exercise(
      name: "Plank",
      description: "Bài tập toàn thân, đặc biệt là cơ bụng và lưng.",
      duration: 2,
      category: "Bụng",
      difficulty: "Trung bình",
      equipment: "Không",
      muscles: "Bụng, Lưng, Vai",
      caloriesBurned: "55 kcal/10 phút",
      imageUrl: "https://tse2.mm.bing.net/th/id/OIP.lIcDasLLdudJ2iCqfDWtLgHaEK?rs=1"),
  Exercise(
      name: "Crunches",
      description: "Tăng cường cơ bụng trên, bài tập truyền thống.",
      duration: 3,
      category: "Bụng",
      difficulty: "Dễ",
      equipment: "Không",
      muscles: "Cơ bụng trên",
      caloriesBurned: "50 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.JL3Nm-LkUdUEB9i2eUElLQHaEK?rs=1"),
  Exercise(
      name: "Mountain Climbers",
      description: "Bài cardio giúp siết cơ bụng và đốt mỡ.",
      duration: 3,
      category: "Bụng",
      difficulty: "Trung bình",
      equipment: "Không",
      muscles: "Bụng, Toàn thân",
      caloriesBurned: "80 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.IzR7GqPIArvxgPyGPhIl2gHaE8?rs=1"),
  Exercise(
      name: "Leg Raises",
      description: "Cô lập cơ bụng dưới, thực hiện trên sàn.",
      duration: 3,
      category: "Bụng",
      difficulty: "Trung bình",
      equipment: "Không",
      muscles: "Cơ bụng dưới",
      caloriesBurned: "65 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.EpNyE3g_wGSxw9n_9xQ1AgHaHa?rs=1"),
  Exercise(
      name: "Bicycle Crunches",
      description: "Tác động toàn bộ cơ bụng bằng chuyển động chân.",
      duration: 3,
      category: "Bụng",
      difficulty: "Trung bình",
      equipment: "Không",
      muscles: "Cơ bụng trên, xiên",
      caloriesBurned: "70 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.QMPkzImvgoacIlS5DEB7AQHaEK?rs=1"),
  Exercise(
      name: "Russian Twists",
      description: "Tăng cường cơ xiên bụng bằng vặn người.",
      duration: 3,
      category: "Bụng",
      difficulty: "Trung bình",
      equipment: "Tạ tay nhẹ hoặc không",
      muscles: "Cơ xiên bụng",
      caloriesBurned: "60 kcal/10 phút",
      imageUrl: "https://tse2.mm.bing.net/th/id/OIP.3aZG8Z6ptNDgP3hDXiDA7AHaHa?rs=1"),
  Exercise(
      name: "V-Ups",
      description: "Kết hợp gập bụng và nâng chân cùng lúc.",
      duration: 4,
      category: "Bụng",
      difficulty: "Khó",
      equipment: "Không",
      muscles: "Cơ bụng toàn phần",
      caloriesBurned: "85 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.EIsHLjGvDEbKx4FaEbkX9QHaFj?rs=1"),
  Exercise(
      name: "Flutter Kicks",
      description: "Tác động mạnh đến cơ bụng dưới và xiên.",
      duration: 3,
      category: "Bụng",
      difficulty: "Trung bình",
      equipment: "Không",
      muscles: "Cơ bụng dưới",
      caloriesBurned: "65 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.xUyKCGvAUKRPcOvQo1zQhQHaEK?rs=1"),
  Exercise(
      name: "Toe Touches",
      description: "Nâng người chạm mũi chân, siết cơ bụng trên.",
      duration: 3,
      category: "Bụng",
      difficulty: "Dễ",
      equipment: "Không",
      muscles: "Cơ bụng trên",
      caloriesBurned: "55 kcal/10 phút",
      imageUrl: "https://tse1.mm.bing.net/th/id/OIP.5k6mGxDFTe4mqjGj7AFwDgHaE8?rs=1"),
  Exercise(
      name: "Hollow Hold",
      description: "Giữ cơ bụng trong trạng thái căng liên tục.",
      duration: 2,
      category: "Bụng",
      difficulty: "Khó",
      equipment: "Không",
      muscles: "Toàn bộ cơ bụng",
      caloriesBurned: "75 kcal/10 phút",
      imageUrl: "https://tse3.mm.bing.net/th/id/OIP.Yvx6ToTxuTvAP_e5uCdHfAHaE8?rs=1"),
];

final List<Exercise> shoulderExercises = [
  Exercise(
    name: "Overhead Press",
    description: "Tăng cường sức mạnh vai bằng cách đẩy tạ qua đầu.",
    duration: 4,
    category: "Vai",
    difficulty: "Trung bình",
    equipment: "Tạ đòn hoặc tạ đơn",
    muscles: "Vai trước, Vai giữa",
    caloriesBurned: "85 kcal/10 phút",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.U2FbTbKFnrW6zjJGS0U9_wHaE7?rs=1",
  ),
  Exercise(
    name: "Lateral Raise",
    description: "Nâng tạ sang ngang để tác động vai giữa.",
    duration: 3,
    category: "Vai",
    difficulty: "Trung bình",
    equipment: "Tạ đơn",
    muscles: "Vai giữa",
    caloriesBurned: "65 kcal/10 phút",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.4sNj6aG0K0H_5oUP5mOjYwHaE7?rs=1",
  ),
  Exercise(
    name: "Front Raise",
    description: "Nâng tạ ra phía trước để tập trung vai trước.",
    duration: 3,
    category: "Vai",
    difficulty: "Trung bình",
    equipment: "Tạ đơn",
    muscles: "Vai trước",
    caloriesBurned: "60 kcal/10 phút",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.JSeIkvSXLpRI0MS1VNd78AHaE7?rs=1",
  ),
  Exercise(
    name: "Arnold Press",
    description: "Biến thể của overhead press do Arnold Schwarzenegger sáng tạo.",
    duration: 4,
    category: "Vai",
    difficulty: "Khó",
    equipment: "Tạ đơn",
    muscles: "Vai trước, Vai giữa",
    caloriesBurned: "90 kcal/10 phút",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.HiSnTCpTIVzD5oxmC-r-XQHaEK?rs=1",
  ),
  Exercise(
    name: "Rear Delt Fly",
    description: "Tập trung vào cơ vai sau bằng động tác mở rộng tay ra sau.",
    duration: 3,
    category: "Vai",
    difficulty: "Trung bình",
    equipment: "Tạ đơn hoặc máy",
    muscles: "Vai sau",
    caloriesBurned: "65 kcal/10 phút",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.UTrpbmb1AG_QB3cGHmkzMwHaFj?rs=1",
  ),
  Exercise(
    name: "Face Pull",
    description: "Kéo dây cáp ngang mặt để kích hoạt vai sau và cơ ổ vai.",
    duration: 3,
    category: "Vai",
    difficulty: "Trung bình",
    equipment: "Máy kéo cáp",
    muscles: "Vai sau, Lưng trên",
    caloriesBurned: "70 kcal/10 phút",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.IkpcqAtjN2czY_Y2d2K9GQHaE8?rs=1",
  ),
  Exercise(
    name: "Dumbbell Shrug",
    description: "Tập trung vào cơ cầu vai bằng cách nhún vai với tạ.",
    duration: 2,
    category: "Vai",
    difficulty: "Dễ",
    equipment: "Tạ đơn",
    muscles: "Cầu vai (trapezius)",
    caloriesBurned: "55 kcal/10 phút",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.vQz4MHWHslMOUh1qQmnNzgHaE8?rs=1",
  ),
  Exercise(
    name: "Push Press",
    description: "Biến thể explosive của overhead press kết hợp chân.",
    duration: 4,
    category: "Vai",
    difficulty: "Khó",
    equipment: "Tạ đòn",
    muscles: "Vai, Cẳng tay, Chân",
    caloriesBurned: "95 kcal/10 phút",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.e4F-LfiQY3KKv6xqKVCuMgHaE8?rs=1",
  ),
  Exercise(
    name: "Cable Lateral Raise",
    description: "Tác động sâu vai giữa bằng máy cáp.",
    duration: 3,
    category: "Vai",
    difficulty: "Trung bình",
    equipment: "Máy kéo cáp",
    muscles: "Vai giữa",
    caloriesBurned: "65 kcal/10 phút",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.9c46eG6K3nQ5BBdtfHdK9AHaE8?rs=1",
  ),
  Exercise(
    name: "Plate Front Raise",
    description: "Dùng đĩa tạ để nâng trước mặt tập vai trước.",
    duration: 3,
    category: "Vai",
    difficulty: "Trung bình",
    equipment: "Đĩa tạ",
    muscles: "Vai trước",
    caloriesBurned: "60 kcal/10 phút",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.DpvGQdxWvnJv5lHHzIZrkgHaEK?rs=1",
  ),
];

