import 'whey_model.dart';

List<Whey> wheySamples = [
  Whey(
    name: "Allmax Isoflex",
    weight: 2270,
    protein: 27,
    price: 1890000,
    note: "Whey isolate tinh khiết ~90%",
    servingSize: "1 muỗng (30g) – 75 lần dùng",
    proteinRatio: "90%",
    nutritionInfo: "Calories: 120 – Protein: 27g – Carbs: 2g – Fat: 0.5g",
    flavors: "Chocolate, Vanilla, Strawberry, Chocolate Peanut Butter, Chocolate Mint, Banana",
    brand: "Allmax Nutrition",
    origin: "Canada",
    proteinType: "Ultra-Filtered Whey Protein Isolate",
    imageUrl: "https://bizweb.dktcdn.net/100/011/344/products/allmax-nutrition-isoflex-2-lbs-907-g.jpg?v=1638591733037",
  ),

  Whey(
    name: "Mutant Iso Surge",
    weight: 2268,
    protein: 25,
    price: 2550000,
    note: "Whey isolate + concentrate, vị ngon dễ uống",
    servingSize: "1 muỗng (37g) – 61 lần dùng",
    proteinRatio: "68%",
    nutritionInfo: "Calories: 140 – Protein: 25g – Carbs: 5g – Fat: 2g",
    flavors: "Chocolate Fudge Brownie, Cheesecake, Strawberry Milkshake, Cookies & Cream",
    brand: "Mutant",
    origin: "Canada",
    proteinType: "Whey Protein Isolate + Concentrate",
    imageUrl: "https://product.hstatic.net/1000185761/product/mutant-iso-surge-5-lbs-76-servings-triple-chocolate_1120e75a211542898c84ad1998ceb6ef.png",
  ),
  Whey(
    name: "Rule 1 R1 Protein",
    weight: 2268,
    protein: 27,
    price: 2200000,
    note: "Whey tinh khiết, ít tạp chất",
    servingSize: "1 muỗng (33g) – 69 lần dùng",
    proteinRatio: "82%",
    nutritionInfo: "Calories: 110 – Protein: 27g – Carbs: 1g – Fat: 0.5g",
    flavors: "Chocolate Fudge, Vanilla, Cookies & Cream, Chocolate Peanut Butter",
    brand: "Rule 1",
    origin: "USA",
    proteinType: "Isolate + Hydrolysate + Concentrate",
    imageUrl: "https://bizweb.dktcdn.net/100/011/344/products/rule-1-r1-protein-chocolate-fudge-5lbs-900x900-jpeg.jpg?v=1749546750660",
  ),
  Whey(
    name: "Platinum Hydro Whey",
    weight: 1588,
    protein: 30,
    price: 2770000,
    note: "Hydrolyzed whey hấp thu cực nhanh",
    servingSize: "1 muỗng (39g) – 40 lần dùng",
    proteinRatio: "76%",
    nutritionInfo: "Calories: 140 – Protein: 30g – Carbs: 2g – Fat: 1g",
    flavors: "Turbo Chocolate, Velocity Vanilla, Super Strawberry",
    brand: "Optimum Nutrition",
    origin: "USA",
    proteinType: "Hydrolyzed Whey Protein Isolate",
    imageUrl: "https://www.thegioiwhey.com/cdn/shop/files/Artboard1_c6615d0e-edaa-4516-8096-c6b55bb3a0a2.png?v=1702954729&width=360",
  ),
  Whey(
    name: "ON Gold Standard",
    weight: 2270,
    protein: 24,
    price: 2480000,
    note: "Bán chạy nhất thế giới",
    servingSize: "1 muỗng (32g) – 71 lần dùng",
    proteinRatio: "75%",
    nutritionInfo: "Calories: 120 – Protein: 24g – Carbs: 3g – Fat: 1g",
    flavors: "Chocolate, Vanilla, Strawberry, Cookies & Cream",
    brand: "Optimum Nutrition",
    origin: "USA",
    proteinType: "Isolate + Concentrate + Peptides",
    imageUrl: "https://bizweb.dktcdn.net/100/011/344/products/on-whey-gold-standard-double-rich-chocolate-5lbs-whey-protein-gymstore-jpeg.jpg?v=1688460849017",
  ),
  Whey(
    name: "BiotechUSA Hydro Whey Zero",
    weight: 2040,
    protein: 30,
    price: 2490000,
    note: "Thủy phân, không đường, không lactose",
    servingSize: "1 muỗng (22g) – 90 lần dùng",
    proteinRatio: "90%",
    nutritionInfo: "Calories: 80 – Protein: 20g – Carbs: 0.5g – Fat: 0.5g",
    flavors: "Chocolate, Vanilla, Strawberry, Banana",
    brand: "BiotechUSA",
    origin: "Hungary",
    proteinType: "Hydrolyzed Whey Protein Isolate",
    imageUrl: "https://bizweb.dktcdn.net/100/011/344/products/biotechusa-hydro-whey-zero-vanilla-1-8kg-gymstore-jpeg.jpg?v=1690008647117",
  ),
  Whey(
    name: "Hydropure Nutrabolics",
    weight: 2040,
    protein: 28,
    price: 2250000,
    note: "Dễ tiêu hoá, hấp thu nhanh",
    servingSize: "1 muỗng (32g) – 63 lần dùng",
    proteinRatio: "87%",
    nutritionInfo: "Calories: 120 – Protein: 28g – Carbs: 2g – Fat: 1g",
    flavors: "Chocolate, Vanilla, Cookies & Cream",
    brand: "Nutrabolics",
    origin: "Canada",
    proteinType: "Hydrolyzed Whey Protein Isolate",
    imageUrl: "https://cdn.chiaki.vn/unsafe/0x960/left/top/smart/filters:quality(75)/https://chiaki.vn/upload/product/2024/05/bot-uong-ho-tro-tang-co-1-6lbs-nutrabolics-hydropure-vanilla-milkshake-p11401601-6645bd0937d78-16052024150009.jpg",
  ),
  Whey(
    name: "Amix Isoprime CFM",
    weight: 2270,
    protein: 27,
    price: 2500000,
    note: "Tinh khiết, công nghệ CFM",
    servingSize: "1 muỗng (30g) – 76 lần dùng",
    proteinRatio: "90%",
    nutritionInfo: "Calories: 110 – Protein: 27g – Carbs: 0g – Fat: 0g",
    flavors: "Chocolate, Strawberry, Vanilla",
    brand: "Amix",
    origin: "Europe",
    proteinType: "CFM Whey Protein Isolate",
    imageUrl: "https://amix-nutrition.com/data/image/w1024h1024/4/isoprime-cfm-isolate-3894.jpg",
  ),
];
