import 'food_model.dart';

List<Food> foodSamples = [
  Food(
    name: "Ức gà luộc",
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
    category: "Thịt",
    unit: "100g",
    description: "Ức gà không da, luộc chín, giàu protein và ít béo.",
    brand: "—",
    origin: "Việt Nam",
    imageUrl: "assets/food/banana.webp",
  ),
  Food(
    name: "Trứng gà",
    calories: 155,
    protein: 13,
    fat: 11,
    carbs: 1.1,
    category: "Trứng",
    unit: "100g (~2 quả)",
    description: "Thực phẩm giàu dinh dưỡng, chứa đầy đủ axit amin thiết yếu.",
    origin: "Việt Nam",
    imageUrl: "assets/food/egg.webp",
  ),
  Food(
    name: "Yến mạch cán dẹt",
    calories: 389,
    protein: 16.9,
    fat: 6.9,
    carbs: 66,
    category: "Ngũ cốc",
    unit: "100g",
    description: "Nguồn carbs phức tốt cho tim mạch, giàu chất xơ beta-glucan.",
    brand: "Quaker",
    origin: "Mỹ",
    imageUrl: "assets/food/wheat.webp",
  ),
  Food(
    name: "Khoai lang luộc",
    calories: 86,
    protein: 1.6,
    fat: 0.1,
    carbs: 20.1,
    category: "Tinh bột",
    unit: "100g",
    description: "Thực phẩm giàu chất xơ, đường tự nhiên, tốt cho hệ tiêu hóa.",
    origin: "Việt Nam",
    imageUrl: "assets/food/sweetpotato.webp",
  ),
  Food(
    name: "Cá hồi phi lê",
    calories: 208,
    protein: 20,
    fat: 13,
    carbs: 0,
    category: "Hải sản",
    unit: "100g",
    description: "Nguồn protein cao cấp, giàu omega-3 tốt cho tim mạch và não.",
    origin: "Na Uy",
    imageUrl: "assets/food/salmon.jpg",
  ),
  Food(
    name: "Bông cải xanh hấp",
    calories: 34,
    protein: 2.8,
    fat: 0.4,
    carbs: 7,
    category: "Rau củ",
    unit: "100g",
    description: "Chứa nhiều vitamin C, chất xơ và chất chống oxy hóa.",
    origin: "Việt Nam",
    imageUrl: "assets/food/brocolli.jpg",
  ),
  Food(
    name: "Chuối chín",
    calories: 89,
    protein: 1.1,
    fat: 0.3,
    carbs: 23,
    category: "Trái cây",
    unit: "100g (~1 quả)",
    description: "Nguồn năng lượng nhanh, giàu kali và vitamin B6.",
    origin: "Việt Nam",
    imageUrl: "assets/food/banana.webp",
  ),
  Food(
    name: "Cơm trắng",
    calories: 130,
    protein: 2.7,
    fat: 0.3,
    carbs: 28,
    category: "Tinh bột",
    unit: "100g (1 bát nhỏ)",
    description: "Nguồn cung cấp năng lượng chính, dễ tiêu hóa.",
    origin: "Việt Nam",
    imageUrl: "assets/food/rice.webp",
  ),
  Food(
    name: "Đậu hũ trắng",
    calories: 76,
    protein: 8,
    fat: 4.8,
    carbs: 1.9,
    category: "Thực vật",
    unit: "100g",
    description: "Nguồn protein thực vật tốt, chứa canxi và sắt.",
    origin: "Việt Nam",
    imageUrl: "assets/food/tofu.jpg",
  ),
  Food(
    name: "Sữa chua không đường",
    calories: 59,
    protein: 10,
    fat: 0.4,
    carbs: 3.6,
    category: "Sữa & chế phẩm",
    unit: "100g (1 hộp)",
    description: "Giàu probiotics, tốt cho hệ tiêu hóa và miễn dịch.",
    brand: "Vinamilk",
    origin: "Việt Nam",
    imageUrl: "assets/food/yoghurt.webp",
  ),
];
